routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Route::prefix('sim')->group(function () {
    Route::get('', 'HomeController@sim')->name('sim.index');
});

Route::resource('users', 'UserController')->except([
    'index',
    'store',
    'create',
    'update'
]);
Route::patch('users/{user}', 'UserController@update')->name('users.update')->middleware('can_edit');

Route::resource('suggestions', 'SuggestionController');
Route::patch('suggestions/{suggestion}/status', 'SuggestionController@status')->name('suggestions.status');

Route::resource('universes', 'UniverseController')->except([
    'edit',
    'update'
]);

// TODO move to route groups and figure out why it ain't working
Route::middleware('can_edit_universe')->group(function () {
    Route::get('universes/{universe}/edit', 'UniverseController@edit')->name('universes.edit');
    Route::patch('universes/{universe}', 'UniverseController@update')->name('universes.update');
});

Route::post('universes/duplicate_slug', 'UniverseController@duplicateSlug');
Route::post('series/duplicate_slug', 'SeriesController@duplicateSlug');

// TODO fix your fucking routing 'cause it's becoming a mess
Route::prefix('universes')->group(function () {
    Route::prefix('{universe}')->group(function () {
        Route::delete('{series}/{season}/races/{race}', 'RaceController@destroy')->name('races.delete');

        Route::middleware('can_edit_universe')->group(function () {
            // Series
            Route::get('series/create', 'SeriesController@create')->name('series.create');
            Route::post('series', 'SeriesController@store')->name('series.store');
            Route::get('series/{series}/edit', 'SeriesController@edit')->name('series.edit');
            Route::patch('series/{series}', 'SeriesController@update')->name('series.update');

            // Teams
            Route::get('{series}/teams/create', 'TeamController@create')->name('teams.create');
            Route::get('{series}/teams/{team}/edit', 'TeamController@edit')->name('teams.edit');
            Route::post('{series}/teams', 'TeamController@store')->name('teams.store');
            Route::post('{series}/teams/{team}', 'TeamController@update')->name('teams.update');

            // Drivers
            Route::get('drivers/create', 'DriverController@create')->name('drivers.create');
            Route::post('drivers', 'DriverController@store')->name('drivers.store');
            Route::get('drivers/{driver}/edit', 'DriverController@edit')->name('drivers.edit');
            Route::patch('driver/{driver}', 'DriverController@update')->name('drivers.update');

            // Engines
            Route::get('{series}/engines/create', 'EngineController@create')->name('engines.create');
            Route::post('{series}/engine', 'EngineController@store')->name('engines.store');
            Route::get('{series}/engines/{engine}/edit', 'EngineController@edit')->name('engines.edit');
            Route::patch('{series}/engine/{engine}', 'EngineController@update')->name('engines.update');

            // Seasons
            Route::get('{series}/seasons/create', 'SeasonController@create')->name('seasons.create');
            Route::post('{series}/seasons', 'SeasonController@store')->name('seasons.store');
            Route::get('{series}/seasons/{season}/edit', 'SeasonController@edit')->name('seasons.edit');
            Route::patch('{series}/seasons/{season}', 'SeasonController@update')->name('seasons.update');

            // Races
            Route::get('{series}/seasons/{season}/races/create', 'RaceController@create')->name('races.create');
            Route::post('{series}/{season}/races', 'RaceController@store')->name('races.store');
            Route::get('{series}/seasons/{season}/races/{race}/edit', 'RaceController@edit')->name('races.edit');
            Route::patch('{series}/{season}/races/{race}', 'RaceController@update')->name('races.update');

            // Points
            Route::get('{series}/{season}/points', 'SeasonController@points')->name('seasons.points');
            Route::post('{series}/seasons/{season}/points', 'SeasonController@storePoints')->name('seasons.points.store');

            // Reliability
            Route::get('{series}/{season}/reliability', 'SeasonController@reliability')->name('seasons.reliability');
            Route::post('{series}/{season}/reliability', 'SeasonController@storeReliability')->name('seasons.reliability.store');

            // Qualifying settings
            Route::get('{series}/{season}/qualifying', 'SeasonController@qualifying')->name('seasons.qualifying');
            Route::post('{series}/{season}/qualifying', 'SeasonController@storeQualifying')->name('seasons.qualifying.store');

            // Lineups
            Route::get('{series}/{season}/lineup', 'LineupController@create')->name('seasons.lineups.create');
            Route::get('{series}/{season}/lineups/{lineup}/edit', 'LineupController@edit')->name('seasons.lineups.edit');

            Route::post('{series}/{season}/start', 'SeasonController@start')->name('seasons.start');
        });

        Route::middleware('can_see_universe')->group(function () {
            // Series
            Route::get('{series}', 'SeriesController@index')->name('series.index');
            Route::get('series/{series}', 'SeriesController@show')->name('series.show');

            // Seasons
            Route::get('{series}/season/{season}/{tab?}', 'SeasonController@show')->name('seasons.show');
        });
    });
});

Auth::routes();

app/Models/Suggestion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use App\Models\User;

class Suggestion extends Model
{
    protected $fillable = [
        'title', 'description'
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(SuggestionCategory::class);
    }

    /**
     * @return BelongsTo
     */
    public function status(): BelongsTo
    {
        return $this->belongsTo(SuggestionStatus::class);
    }
}

app/Http/Controllers/SuggestionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NewSuggestionRequest;
use App\Http\Requests\UpdateSuggestionRequest;
use App\Models\Suggestion;
use App\Models\SuggestionCategory;
use App\Models\SuggestionStatus;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SuggestionController extends Controller
{
    /**
     * @return Renderable
     */
    public function index(): Renderable
    {
        $suggestions = Suggestion::all();

        return view('suggestions.index', [
            'suggestions' => $suggestions
        ]);
    }

    /**
     * @return Renderable
     */
    public function create(): Renderable
    {
        $categories = SuggestionCategory::orderBy('name', 'asc')->get();

        return view('suggestions.create', [
            'categories' => $categories
        ]);
    }

    /**
     * @param NewSuggestionRequest $request
     * @return RedirectResponse
     */
    public function store(NewSuggestionRequest $request): RedirectResponse
    {
        $suggestion = Suggestion::create([
            'title' => $request->get('title'),
            'description' => $request->get('description')
        ]);

        $category = SuggestionCategory::find((int) $request->get('category_id'));
        $status = SuggestionStatus::where('name', 'new')->first();

        $suggestion->category()->associate($category);
        $suggestion->status()->associate($status);
        $suggestion->user()->associate(Auth::user());

        $suggestion->save();

        return redirect()->route('suggestions.index');
    }

    /**
     * @param Suggestion $suggestion
     * @return Renderable
     */
    public function edit(Suggestion $suggestion): Renderable
    {
        $categories = SuggestionCategory::orderBy('name', 'asc')->get();

        return view('suggestions.edit', [
            'suggestion' => $suggestion,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateSuggestionRequest $request
     * @param  Suggestion $suggestion
     * @return RedirectResponse
     */
    public function update(UpdateSuggestionRequest $request, Suggestion $suggestion): RedirectResponse
    {
        $suggestion->title = $request->get('title');
        $suggestion->description = $request->get('description');

        $category = SuggestionCategory::find((int) $request->get('category_id'));

        $suggestion->category()->associate($category);
        $suggestion->save();

        return redirect()->route('suggestions.index');
    }

    /**
     * Changes suggestion status
     *
     * @param Request $request
     * @param Suggestion $suggestion
     * @return RedirectResponse
     */
    public function status(Request $request, Suggestion $suggestion): RedirectResponse
    {
        $statusName = "{$request->get('action')}ed";
        $status = SuggestionStatus::where('name', $statusName)->first();

        $suggestion->status()->associate($status);
        $suggestion->save();

        $request->session()->flash('message', 'Status updated');
        return redirect()->route('suggestions.index');
    }
}

resources/views/suggestions/create.blade.php
@extends('layouts.main')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>New suggestion</h2>
        </div>

        <div class="card-body">
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            <p>{{ $error }}</p>
            @endforeach
            @endif
        </div>

        <form action="{{ route('suggestions.store') }}" method="POST">
            @csrf

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title') }}"
                    placeholder="Title" required>
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control"
                    placeholder="Description" required>{{ old('description') }}</textarea>
            </div>

            <div class="form-group">
                <label for="category_id">Category</label>
                <select name="category_id" id="category_id" class="form-control" required>
                    @foreach ($categories as $category)
                    <option value="{{ $category->id }}">{{ ucfirst($category->name) }}</option>
                    @endforeach
                </select>
            </div>

            <button type="submit" class="btn btn-secondary">Save suggestion</button>
        </form>
    </div>
</div>
@endsection

resources/views/suggestions/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>Edit suggestion {{ $suggestion->title }}</h2>
            </div>
            <div class="card-body">
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach
                @endif

                <form action="{{ route('suggestions.update', $suggestion) }}" method="POST">
                    @csrf
                    @method('PATCH')

                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ old('title') ?? $suggestion->title }}" placeholder="Title" required>
                    </div>

                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" cols="30" rows="10" class="form-control" placeholder="Description" required>{{ old('description') ?? $suggestion->description }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="category_id">Category</label>
                        <select name="category_id" id="category_id" class="form-control" required>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}" {{ $category->id === $suggestion->category->id ? 'selected' : '' }}>{{ ucfirst($category->name) }}</option>
                            @endforeach
                        </select>
                    </div>

                    <button type="submit" class="btn btn-secondary">Update</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/suggestions/index.blade.php
@extends('layouts.main')

@section('content')
<div class="container">
    <h2>Suggestions</h2>

    @auth
    <a href="{{ route('suggestions.create') }}" class="btn btn-primary btn-small">Submit suggestion</a>
    @endauth
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Category</th>
                <th>Status</th>
                <th></th>
                @if (Auth::check() && Auth::user()->isAdmin())
                <th></th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach ($suggestions as $suggestion)
            <tr>
                <td>{{ $suggestion->id }}</td>
                <td>{{ $suggestion->title }}</td>
                <td>
                    <span class="label" style="background-color: {{$suggestion->category->colour}}">
                        {{ ucfirst($suggestion->category->name) }}
                    </span>
                </td>
                <td>
                    <span class="label" style="background-color: {{$suggestion->status->colour}}">
                        {{ ucfirst($suggestion->status->name) }}
                    </span>
                </td>
                <td>
                    @if (Auth::check() && (Auth::user()->isAdmin() || Auth::user()->id === $suggestion->user->id))
                    <a href="{{ route('suggestions.edit', $suggestion) }}" class="btn btn-secondary btn-small">
                        Edit
                    </a>
                    @endif
                </td>
                @if (Auth::check() && Auth::user()->isAdmin())
                <td>
                    <form action="{{ route('suggestions.status', $suggestion) }}" method="POST">
                        @csrf
                        @method('PATCH')

                        @if ($suggestion->status->name !== 'accepted')
                        <button type="submit" name="action" value="accept"
                            class="btn btn-success btn-small">Accept</button>
                        @endif
                        @if ($suggestion->status->name !== 'rejected')
                        <button type="submit" name="action" value="reject"
                            class="btn btn-danger btn-small">Reject</button>
                        @endif
                    </form>
                </td>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection